### ISSUE TITLE
guzzlehttp/guzzle version 7.0

### ISSUE THREAD

**Issue by Levivb** [prewk/xml-string-streamer-guzzle#5]
Any chance this package can get support for `guzzlehttp/guzzle` version 7? :D

We use this package quite heavily and it blocks the usage of https://github.com/therobfonz/laravel-mandrill-driver/blob/master/composer.json which requires guzzle 7.0

https://packagist.org/packages/guzzlehttp/guzzle
https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

**Comment by prewk** [comment]
Yeah sure, the reason it's 6.0 is to support a reaaally old PHP version but people stuck there can just pin their version I guess.

It's a pretty simple implementation if you wanna try a PR: https://github.com/prewk/xml-string-streamer-guzzle/blob/master/src/XmlStringStreamer/Stream/Guzzle.php

I'm a bit short of time so can't guarantee to get it up very fast.

**Comment by Levivb** [comment]
Thanks for your response. I noticed the guzzle usage in this package is pretty vanilla, making the update quite easy. I'll check it out later tonight (I hope ;)

**Comment by prewk** [comment]
Sounds good, write here if it doesn't work out and I'll get an email :)

**Comment by yushkevichv** [comment]
@Levivb Support guzzle 7.0 added at 1.0.0 version 

@prewk  I think, this issue should be closed :)

**Comment by Levivb** [comment]
Thanks! 😀
